[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/magazine"
  to = "/magazine/index.html"
  status = 200

[[redirects]]
  from = "/magazine/"
  to = "/magazine/index.html"
  status = 200

[[redirects]]
  from = "/notes"
  to = "/notes/index.html"
  status = 200

[[redirects]]
  from = "/notes/"
  to = "/notes/index.html"
  status = 200

[[redirects]]
  from = "/works"
  to = "/works/index.html"
  status = 200

[[redirects]]
  from = "/works/"
  to = "/works/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/about/"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin/index.html"
  status = 200
